export const cmdImport = 'gjs-open-import-webpage';
export const cmdDeviceDesktop = 'set-device-desktop';
export const cmdDeviceTablet = 'set-device-tablet';
export const cmdDeviceMobile = 'set-device-mobile';
export const clear = 'canvas-clear'; //clear canvas
export const exportTemplate = 'export-template'; //export template
export const showFrames = 'sw-visibility'; //show visibility
export const openStyles = 'show-styles'; //style manager
export const openTraits = 'show-traits'; //traits manager
export const openLayers = 'show-layers'; //layers manager
export const openBlocks = 'show-blocks'; //blocks manager
export const ful = 'fullscreen'; //fullscreen
export const preview = 'preview'; //preview
