/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'basic-portal-identity': BasicPortalIdentity;
    templates: Template;
    'design-system': DesignSystem;
    'themes-style': ThemesStyle;
    'mega-menu': MegaMenu;
    pages: Page;
    'page-Template': PageTemplate;
    media: Media;
    'page-builder': PageBuilder;
    users: User;
    'section-templates': SectionTemplate;
    brand: Brand;
  };
  globals: {};
}
export interface BasicPortalIdentity {
  id: string;
  career_portal_name?: string;
  portal_url?: string;
  portal_id?: string;
  default_locale?: 'US' | 'ES';
  default_language?: 'English' | 'Spanish';
  company_name?: string;
  tracking_pixel?: string;
  bing_webmaster?: string;
  google_webmaster?: string;
  google_analytics?: string;
  google_id?: string;
  micro_sites: 'sub_domain' | 'sub_directories';
  default_brand?: 'brand1' | 'brand2';
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Template {
  id: string;
  title: string;
  type: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface DesignSystem {
  id: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface ThemesStyle {
  id: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface MegaMenu {
  id: string;
  title: string;
  parent_menu?: string | MegaMenu;
  menu_section?: 'header' | 'footer';
  nav: {
    link: {
      type?: 'page' | 'custom';
      label: string;
      page: string | Page;
      url: string;
    };
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Page {
  id: string;
  title: string;
  pageType: string;
  pageId?: string;
  pageCode?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface PageTemplate {
  id: string;
  title: string;
  pageAssets?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Media {
  id: string;
  mediaType?: 'Icon' | 'Photo' | 'Video';
  icon: string;
  photo: string;
  video: string;
  keywords: string;
  description: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface PageBuilder {
  id: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface User {
  id: string;
  first_name?: string;
  last_name?: string;
  role?: 'user' | 'admin';
  defaultStyle?: {
    [k: string]: unknown;
  };
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface SectionTemplate {
  id: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Brand {
  id: string;
  career_portal_name?: string;
  portal_url?: string;
  portal_id?: string;
  default_locale?: 'us_EN' | 'es_ES';
  default_language?: 'en' | 'es';
  company_name?: string;
  tracking_pixel?: string;
  bing_webmaster?: string;
  google_webmaster?: string;
  google_analytics?: string;
  google_id?: string;
  page_title?: string;
  meta_keywords?: string;
  meta_description?: string;
  microsite_setting?: 'sub_domain' | 'sub_directories';
  brands: {
    brand_name?: string;
    brand_identifier?: string;
    microsoft_identifier?: string;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
  password?: string;
}
